export const countries = 
[
  { code: 'PE 🇵🇪', name: 'Perú', prefix: '+51' },
  { code: 'MX 🇲🇽', name: 'México', prefix: '+52' },
  { code: 'CO 🇨🇴', name: 'Colombia', prefix: '+57' },
  { code: 'AR 🇦🇷', name: 'Argentina', prefix: '+54' },
  { code: 'CL 🇨🇱', name: 'Chile', prefix: '+56' },
  { code: 'ES 🇪🇸', name: 'España', prefix: '+34' },
  { code: 'US 🇺🇸', name: 'Estados Unidos', prefix: '+1' },
  { code: 'HN 🇭🇳', name: 'Honduras', prefix: '+504' },
  { code: 'BR 🇧🇷', name: 'Brasil', prefix: '+55' },
  { code: 'BO 🇧🇴', name: 'Bolivia', prefix: '+591' },
  { code: 'EC 🇪🇨', name: 'Ecuador', prefix: '+593' },
  { code: 'UY 🇺🇾', name: 'Uruguay', prefix: '+598' },
  { code: 'PY 🇵🇾', name: 'Paraguay', prefix: '+595' },
  { code: 'VE 🇻🇪', name: 'Venezuela', prefix: '+58' },
  { code: 'GT 🇬🇹', name: 'Guatemala', prefix: '+502' },
  { code: 'CR 🇨🇷', name: 'Costa Rica', prefix: '+506' },
  { code: 'NI 🇳🇮', name: 'Nicaragua', prefix: '+505' },
  { code: 'SV 🇸🇻', name: 'El Salvador', prefix: '+503' },
  { code: 'DO 🇩🇴', name: 'República Dominicana', prefix: '+1-809' },
  { code: 'CU 🇨🇺', name: 'Cuba', prefix: '+53' },
  { code: 'PA 🇵🇦', name: 'Panamá', prefix: '+507' },
  { code: 'CA 🇨🇦', name: 'Canadá', prefix: '+1' },
  { code: 'GB 🇬🇧', name: 'Reino Unido', prefix: '+44' },
  { code: 'FR 🇫🇷', name: 'Francia', prefix: '+33' },
  { code: 'DE 🇩🇪', name: 'Alemania', prefix: '+49' },
  { code: 'IT 🇮🇹', name: 'Italia', prefix: '+39' },
  { code: 'PT 🇵🇹', name: 'Portugal', prefix: '+351' },
  { code: 'JP 🇯🇵', name: 'Japón', prefix: '+81' },
  { code: 'CN 🇨🇳', name: 'China', prefix: '+86' },
  { code: 'KR 🇰🇷', name: 'Corea del Sur', prefix: '+82' },
  { code: 'IN 🇮🇳', name: 'India', prefix: '+91' },
  { code: 'AU 🇦🇺', name: 'Australia', prefix: '+61' },
  { code: 'ZA 🇿🇦', name: 'Sudáfrica', prefix: '+27' },
  { code: 'RU 🇷🇺', name: 'Rusia', prefix: '+7' },
  { code: 'NL 🇳🇱', name: 'Países Bajos', prefix: '+31' },
  { code: 'BE 🇧🇪', name: 'Bélgica', prefix: '+32' },
  { code: 'CH 🇨🇭', name: 'Suiza', prefix: '+41' },
  { code: 'SE 🇸🇪', name: 'Suecia', prefix: '+46' },
  { code: 'NO 🇳🇴', name: 'Noruega', prefix: '+47' },
  { code: 'DK 🇩🇰', name: 'Dinamarca', prefix: '+45' },
  { code: 'FI 🇫🇮', name: 'Finlandia', prefix: '+358' },
  { code: 'GR 🇬🇷', name: 'Grecia', prefix: '+30' },
  { code: 'TR 🇹🇷', name: 'Turquía', prefix: '+90' },
  { code: 'EG 🇪🇬', name: 'Egipto', prefix: '+20' },
  { code: 'MA 🇲🇦', name: 'Marruecos', prefix: '+212' },
  { code: 'NG 🇳🇬', name: 'Nigeria', prefix: '+234' },
  { code: 'NZ 🇳🇿', name: 'Nueva Zelanda', prefix: '+64' },
  { code: 'SG 🇸🇬', name: 'Singapur', prefix: '+65' },
  { code: 'TH 🇹🇭', name: 'Tailandia', prefix: '+66' },
  { code: 'IE 🇮🇪', name: 'Irlanda', prefix: '+353' }
]
;
