export const countries = 
[
  { code: 'PE', name: 'Perú', prefix: '+51', flag: '🇵🇪' },
  { code: 'MX', name: 'México', prefix: '+52', flag: '🇲🇽' },
  { code: 'CO', name: 'Colombia', prefix: '+57', flag: '🇨🇴' },
  { code: 'AR', name: 'Argentina', prefix: '+54', flag: '🇦🇷' },
  { code: 'CL', name: 'Chile', prefix: '+56', flag: '🇨🇱' },
  { code: 'ES', name: 'España', prefix: '+34', flag: '\u{1F1EA}\u{1F1F8}' },
  { code: 'US', name: 'Estados Unidos', prefix: '+1', flag: '🇺🇸' },
  { code: 'HN', name: 'Honduras', prefix: '+504', flag: '🇭🇳' },
  { code: 'BR', name: 'Brasil', prefix: '+55', flag: '🇧🇷' },
  { code: 'BO', name: 'Bolivia', prefix: '+591', flag: '🇧🇴' },
  { code: 'EC', name: 'Ecuador', prefix: '+593', flag: '🇪🇨' },
  { code: 'UY', name: 'Uruguay', prefix: '+598', flag: '🇺🇾' },
  { code: 'PY', name: 'Paraguay', prefix: '+595', flag: '🇵🇾' },
  { code: 'VE', name: 'Venezuela', prefix: '+58', flag: '🇻🇪' },
  { code: 'GT', name: 'Guatemala', prefix: '+502', flag: '🇬🇹' },
  { code: 'CR', name: 'Costa Rica', prefix: '+506', flag: '🇨🇷' },
  { code: 'NI', name: 'Nicaragua', prefix: '+505', flag: '🇳🇮' },
  { code: 'SV', name: 'El Salvador', prefix: '+503', flag: '🇸🇻' },
  { code: 'DO', name: 'República Dominicana', prefix: '+1-809', flag: '🇩🇴' },
  { code: 'CU', name: 'Cuba', prefix: '+53', flag: '🇨🇺' },
  { code: 'PA', name: 'Panamá', prefix: '+507', flag: '🇵🇦' },
  { code: 'CA', name: 'Canadá', prefix: '+1', flag: '🇨🇦' },
  { code: 'GB', name: 'Reino Unido', prefix: '+44', flag: '🇬🇧' },
  { code: 'FR', name: 'Francia', prefix: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Alemania', prefix: '+49', flag: '🇩🇪' },
  { code: 'IT', name: 'Italia', prefix: '+39', flag: '🇮🇹' },
  { code: 'PT', name: 'Portugal', prefix: '+351', flag: '🇵🇹' },
  { code: 'JP', name: 'Japón', prefix: '+81', flag: '🇯🇵' },
  { code: 'CN', name: 'China', prefix: '+86', flag: '🇨🇳' },
  { code: 'KR', name: 'Corea del Sur', prefix: '+82', flag: '🇰🇷' },
  { code: 'IN', name: 'India', prefix: '+91', flag: '🇮🇳' },
  { code: 'AU', name: 'Australia', prefix: '+61', flag: '🇦🇺' },
  { code: 'ZA', name: 'Sudáfrica', prefix: '+27', flag: '🇿🇦' },
  { code: 'RU', name: 'Rusia', prefix: '+7', flag: '🇷🇺' },
  { code: 'NL', name: 'Países Bajos', prefix: '+31', flag: '🇳🇱' },
  { code: 'BE', name: 'Bélgica', prefix: '+32', flag: '🇧🇪' },
  { code: 'CH', name: 'Suiza', prefix: '+41', flag: '🇨🇭' },
  { code: 'SE', name: 'Suecia', prefix: '+46', flag: '🇸🇪' },
  { code: 'NO', name: 'Noruega', prefix: '+47', flag: '🇳🇴' },
  { code: 'DK', name: 'Dinamarca', prefix: '+45', flag: '🇩🇰' },
  { code: 'FI', name: 'Finlandia', prefix: '+358', flag: '🇫🇮' },
  { code: 'GR', name: 'Grecia', prefix: '+30', flag: '🇬🇷' },
  { code: 'TR', name: 'Turquía', prefix: '+90', flag: '🇹🇷' },
  { code: 'EG', name: 'Egipto', prefix: '+20', flag: '🇪🇬' },
  { code: 'MA', name: 'Marruecos', prefix: '+212', flag: '🇲🇦' },
  { code: 'NG', name: 'Nigeria', prefix: '+234', flag: '🇳🇬' },
  { code: 'NZ', name: 'Nueva Zelanda', prefix: '+64', flag: '🇳🇿' },
  { code: 'SG', name: 'Singapur', prefix: '+65', flag: '🇸🇬' },
  { code: 'TH', name: 'Tailandia', prefix: '+66', flag: '🇹🇭' },
  { code: 'IE', name: 'Irlanda', prefix: '+353', flag: '🇮🇪' }
]
;
